### ISSUE TITLE
CIS Benchmark Centos 8

### ISSUE THREAD

**Issue by guillermocol** [massyn/centos-cis-benchmark#35]
Hi Massyn,

It is great how is divided in test cases. Do you know if there is a Centos 8 repository somewhere else in Github. I was not able to find it, but I think there is one somewhere.

Thank you,
Guillermo

**Comment by nikKrian** [comment]
Have u found it ？

**Comment by massyn** [comment]
I'm afraid I won't be able to help with that request.  This is an old repo, and I'm not planning to update it to CentOS 8 (or any other CentOS for that matter).  You're welcome to fork the repo and build your own for the newer OSs.
